apiVersion: apps/v1
kind: Deployment
metadata:
  name: n2-preferred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n2-preferred
  template:
    metadata:
      labels:
        app: n2-preferred
    spec:
      nodeSelector:
        cloud.google.com/compute-class: n2-preferred
      containers:
      - name: test
        image: gcr.io/google_containers/pause
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"