apiVersion: autoscaling.gke.io/v1alpha1
kind: NodeProvisioningConfig
metadata:
  name: spot-preferred
spec:
  priorities:
    rules:
    - byNodeConfig:
        family: n2
        spot: true
        minCores: 16
        minMemoryGb: 64
    - byNodeConfig:
        family: n2d
        spot: true
        minCores: 16
        minMemoryGb: 64
    - byNodeConfig:
        family: n2
        spot: true
    - byNodeConfig:
        family: n2d
        spot: true
    - byNodeConfig:
        family: n2
    - byNodeConfig:
        family: n2d
  nodePoolAutoCreation:
    enabled: true
  activeMigration:
    optimizeRulePriority: true