apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: spot-preferred
spec:
  priorities:
  - machineFamily: n2
    spot: true
    minCores: 16
    minMemoryGb: 64
  - machineFamily: n2d
    spot: true
    minCores: 16
    minMemoryGb: 64
  - machineFamily: n2
    spot: true
  - machineFamily: n2d
    spot: true
  - machineFamily: n2
  - machineFamily: n2d
  activeMigration:
    optimizeRulePriority: true
  autoscalingPolicy:
    consolidationDelayMinutes: 5
  nodePoolAutoCreation:
    enabled: true